language: node_js
node_js: stable
#cache:
#directories:
#- node_modules
before_install:
- npm install -g hexo
#- npm install -g hexo-cli
install:
- npm install
- npm install -S hexo-generator-json-content
- npm install hexo-deployer-git --save

# before_script:
# - npm install -g mocha
# - git clone --branch master https://github.com/dazaza/dazaza.github.io

script:
- hexo clean
- hexo g

after_script:
- git clone ${GH_REF2} public-back
- cp -rf public/* public-back/
- cd public-back
#- git init
- git config user.name "dazaza"
- git config user.email "diglog@126.com"
- git add .
- git commit -m "update from travis-ci"
#- git push --force "https://${GH_TOKEN}@${GH_REF}" origin master
- git push origin master

branches:
only:
- master #watch this branch

env:
  global:
    - GH_REF: github.com/dazaza/dazaza.github.io
    - GH_REF2: https://dazaza:${GH_TOKEN}@github.com/dazaza/dazaza.github.io